version: "3.5"
services: 

  postgres:
    container_name: g_auth_postgres
    image: postgres:12.4
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgres
    networks:
      - db_network

  redis:
    container_name: gauth_redis
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  db_network:
  client_network:


volumes:
  db_data:
