version: "3.5"
services: 

  api:
    build: ./
    image: node:16.15.0
    restart: always
    container_name: g_auth_api
    ports:
        - "${API_PORT}:${API_PORT}"
    expose:
        - "${API_PORT}"
    command: "yarn start:dev"
    volumes:
      - ./:/api
    env_file: .env
    depends_on: 
      - postgres
    networks:
      - api_network
      - db_network
      - client_network


  postgres:
    container_name: g_auth_postgres
    image: postgres:12.4
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgres
    networks:
      - db_network

  redis:
    container_name: gauth_redis
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


  

networks:
  db_network:
  api_network:
  client_network:


volumes:
  db_data:
